{% set version = "21.1.6" %}

package:
  name: flang-activation
  version: {{ version }}

source:
  # unused, but helpful so the bot creates updates automatically;
  # we use the _signature_, which is tiny and thus much faster to download
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "-rc") }}.src.tar.xz.sig
  sha256: 3aa75e60b22a1d0f6a23393f568f38a1d588761d522abc46682c20bed4c5cf1d

build:
  number: 0
  # intentionally only windows (main target) & linux (debuggability)
  skip: true  # [osx]

outputs:
  - name: flang_impl_{{ cross_target_platform }}
    script: install_flang_impl.sh  # [unix]
    # we don't cross-compile on windows -> no symlinks
    requirements:
      - flang ={{ version }}
      - flang-rt_{{ cross_target_platform }} ={{ version }}
      - compiler-rt_{{ cross_target_platform }} ={{ version }}
      - libflang-rt             # [unix]
      - lld                     # [win]
      # for llvm-ar.exe
      - llvm-tools              # [win]
    test:
      commands:
        - {{ CBUILD }}-flang --version  # [unix]
        - {{ CHOST }}-flang --version   # [unix]

  - name: flang_{{ cross_target_platform }}
    script: install_flang.sh  # [unix]
    script: install_flang.bat  # [win]
    run_exports:
      strong:   # [unix]
        - libflang-rt >={{ version }}   # [unix]
    requirements:
      build:
        - sed       # [unix]
        - m2-sed    # [win]
      run:
        - {{ pin_subpackage("flang_impl_" ~ cross_target_platform, exact=True) }}
    test:
      files:
        - hello_world.f90
        - sanitycheckf.f
      commands:
        # on linux we point FC to the symlink; on windows, we point to the binary
        - $FC hello_world.f90       # [unix]
        - "%FC% hello_world.f90"    # [win]
        - ./a.out   # [unix]
        - a.exe     # [win]
        # as used by meson
        - $FC sanitycheckf.f -o sanitycheckf $FFLAGS            # [unix]
        - "%FC% sanitycheckf.f -o sanitycheckf.exe %FFLAGS%"    # [win]
        - ./sanitycheckf    # [unix]
        - sanitycheckf.exe  # [win]

about:
  home: https://flang.llvm.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Flang is a Fortran compiler targeting LLVM.
  dev_url: https://github.com/llvm/llvm-project

extra:
  recipe-maintainers:
    - isuruf
    - h-vetinari
